---
# defaults file for scripts
scripts_python_interpreter: "{{ trix_local }}/python/bin/python3"
scripts_install_path: "{{ trix_sbin }}"
scripts:
  - write_pdsh_genders.py
  - write_slurm_nodes.py
  - write_slurm_partitions.py
scripts_managed_files:
  - /etc/genders
  - /etc/slurm/slurm-nodes.conf
  - /etc/slurm/slurm-partitions.conf

scripts_managed_block_comment1: "# TrinityX will only manage inside 'TrinityX Managed block'."
scripts_managed_block_comment2: "# If manual override is desired, the 'TrinityX Managed block' can be removed."
scripts_managed_block_start_delimiter: "#### TrinityX Managed block start ####"
scripts_managed_block_end_delimiter:   "#### TrinityX Managed block end   ####"
