---
- hosts: controllers

  roles:
  - role: trinity/init
    tags: init

  - role: ansible/write_facts
    tags: init

  - role: trinity/image-create-ubuntu
    tags: image-create
    when: primary

  environment:
    no_proxy: ".{{ trix_domain }},{{ trix_ctrl_ip }},{{ trix_external_fqdn }}"
    NO_PROXY: ".{{ trix_domain }},{{ trix_ctrl_ip }},{{ trix_external_fqdn }}"
