---
- hosts: controllers

  roles:
  - role: trinity/init
    tags: init

  - role: trinity/image-create-redhat
    tags: image-create
    when: primary

  environment:
    no_proxy: ".{{ trix_domain }},{{ trix_ctrl_ip }},{{ trix_external_fqdn }}"
    NO_PROXY: ".{{ trix_domain }},{{ trix_ctrl_ip }},{{ trix_external_fqdn }}"
