---

- set_fact:
    trix_ctrl_interface: '{{ item }}'
  when: inner_loop_var != "" and hostvars[inventory_hostname]['ansible_'+item]['ipv4']['address'] == inner_loop_var
  with_items:
    - "{{ ansible_interfaces }}"

