---

- set_fact:
    trix_ctrl_interface: '{{ item }}'
  when: 
    - inner_loop_var != ""
    - hostvars[inventory_hostname]['ansible_'+item]['ipv4'] is defined
    - hostvars[inventory_hostname]['ansible_'+item]['ipv4']['address'] == inner_loop_var
  with_items:
    - "{{ ansible_interfaces }}"

