---
# tasks file for scripts
# repeat block for each item in the scripts variable
- block:
  - name: Copy scripts to {{ scripts_install_path }}
    copy:
      src: "{{ item }}"
      dest: "{{ scripts_install_path }}"
    with_items: "{{ scripts }}"

  - name: Make scripts executable
    file:
      path: "{{ scripts_install_path }}/{{ item }}"
      mode: 0755
    with_items: "{{ scripts }}"

  - name: "Add #!{{scripts_python_interpreter}} to the scripts"
    lineinfile:
      path: "{{ scripts_install_path }}/{{ item }}"
      line: "#!{{ scripts_python_interpreter }}"
      state: present
      insertbefore: BOF
    with_items: "{{ scripts }}"

  - name: "Ensure comments about managed block is present in (existing) managed files (1)"
    lineinfile:
      path: "{{ item }}"
      line: "{{ scripts_managed_block_comment1 }}" 
      regex: "{{ scripts_managed_block_comment1 }}"
      state: present
    with_items: "{{ scripts_managed_files }}"
    when: item is file

  - name: "Ensure comments about managed block is present in (existing) managed files (2)"
    lineinfile:
      path: "{{ item }}"
      line: "{{ scripts_managed_block_comment2 }}" 
      regex: "{{ scripts_managed_block_comment2 }}"
      state: present
      insertafter: "{{ scripts_managed_block_comment1 }}"
    with_items: "{{ scripts_managed_files }}"
    when: item is file

  - name: "Ensure block start delimiter is present in (existing) managed files"
    lineinfile:
      path: "{{ item }}"
      line: "{{ scripts_managed_block_start_delimiter }}"
      regex: "{{ scripts_managed_block_start_delimiter }}"
      state: present
      insertafter: "{{ scripts_managed_block_comment2 }}"
    with_items: "{{ scripts_managed_files }}"
    when: item is file

  - name: "Ensure block end delimiter is present in (existing) managed files"
    lineinfile:
      path: "{{ item }}"
      line: "{{ scripts_managed_block_end_delimiter }}"
      regex: "{{ scripts_managed_block_end_delimiter }}"
      state: present
      insertafter: "{{ scripts_managed_block_start_delimiter }}"
    with_items: "{{ scripts_managed_files }}"
    when: item is file
